spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootdb
    username: root
    password: 123456

server:
  port: 8099

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
#MyBatis 配置项解读：
#config-location：指定 MyBatis 主配置文件的位置
#mapper-locations：指定 mapper 文件的位置。如果在项目中你的 mapper 文件是按目录来放置，
#那么对应的配置就变成：mapper-locations: classpath:mapper/*/*.xml


#server.port=8099
#server.session.timeout=10
#server.tomcat.uri-encoding=UTF-8
##Mybatis
#mybatis.type-aliases-package=com.ado.demo.domain
#
##mysql
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/springbootdb
#spring.datasource.username=root
#spring.datasource.password=123456
#spring.datasource.max-idle=10
#spring.datasource.max-wait=10000
#spring.datasource.min-idle=5
#spring.datasource.initial-size=5



